var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":15,"id":677,"methods":[{"el":10,"sc":5,"sl":8},{"el":14,"sc":5,"sl":12}],"name":"ProductType","sl":3}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_16":{"methods":[{"sl":12}],"name":"testProductTypeValidation","pass":true,"statements":[{"sl":13}]},"test_18":{"methods":[{"sl":12}],"name":"testProductRequiredValidation","pass":true,"statements":[{"sl":13}]},"test_21":{"methods":[{"sl":12}],"name":"testCreateSKUUsingStripeAccountId","pass":true,"statements":[{"sl":13}]},"test_29":{"methods":[{"sl":12}],"name":"testConvertFromParamsToModelWithouDescriptionAndAttributes","pass":true,"statements":[{"sl":13}]},"test_3":{"methods":[{"sl":12}],"name":"testCreateProduct","pass":true,"statements":[{"sl":13}]},"test_30":{"methods":[{"sl":8},{"sl":12}],"name":"testConvertFromModelToParams","pass":true,"statements":[{"sl":9},{"sl":13}]},"test_38":{"methods":[{"sl":12}],"name":"testRetrieveSKU","pass":true,"statements":[{"sl":13}]},"test_4":{"methods":[{"sl":12}],"name":"testCreateProductUsingStripeAccountId","pass":true,"statements":[{"sl":13}]},"test_47":{"methods":[{"sl":12}],"name":"testInventoryRequiredValidation","pass":true,"statements":[{"sl":13}]},"test_52":{"methods":[{"sl":12}],"name":"testCreateOrderThenChangeShippingMethodThenPay_ConnectedStripeAcc","pass":true,"statements":[{"sl":13}]},"test_57":{"methods":[{"sl":12}],"name":"testCurrencyRequiredValidation","pass":true,"statements":[{"sl":13}]},"test_6":{"methods":[{"sl":12}],"name":"testPriceRequiredValidation","pass":true,"statements":[{"sl":13}]},"test_64":{"methods":[{"sl":12}],"name":"testCreateOrderThenChangeShippingMethodThenPay_MainAcc","pass":true,"statements":[{"sl":13}]},"test_65":{"methods":[{"sl":12}],"name":"testCreateSKU","pass":true,"statements":[{"sl":13}]},"test_73":{"methods":[{"sl":12}],"name":"testUpdateProduct","pass":true,"statements":[{"sl":13}]},"test_87":{"methods":[{"sl":12}],"name":"testRetrieveProduct","pass":true,"statements":[{"sl":13}]},"test_88":{"methods":[{"sl":12}],"name":"testOneMoreProductTypeValidation","pass":true,"statements":[{"sl":13}]},"test_93":{"methods":[{"sl":12}],"name":"testUpdateSKU","pass":true,"statements":[{"sl":13}]},"test_96":{"methods":[{"sl":12}],"name":"testConvertFromParamsToModel","pass":true,"statements":[{"sl":13}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [30], [30], [], [], [30, 88, 65, 4, 16, 87, 6, 38, 64, 29, 47, 52, 73, 3, 93, 57, 96, 18, 21], [30, 88, 65, 4, 16, 87, 6, 38, 64, 29, 47, 52, 73, 3, 93, 57, 96, 18, 21], [], []]
